### ISSUE TITLE
Vim absent.

### ISSUE THREAD

**Issue by 17steen** [Kraaaait/Choco-Packages#1]
I think you forgot to add vim into the list.
Vim is installed on all systems but windows. When I was a sysadmin back in the day, SUN machines, HP/UX, A/IX, Linux, FreeBSD and whatever else you threw at it, Vi or Vim was always installed, it was often the default editor.

But why it is popular among programmers. It is very fast, it has keyboard combos for every action, it has built in regular expression search and search and replace and remember, even if that is available now, it was super rare just a few years back.

Vim has a very healthy plugin architecture and plenty of plugins to do pretty much everything you want to.

If you have a look at a keyboard, you see most of them are split in 4 parts, F keys, keyboard, middle keyboard with page up and down and such and then numeric pad. You can, and should, use Vim just with the small keyboard, so your fingers never need to travel and you should not loose your train of thought, or break up any work by either removing hand from keyboard to the arrow keys or a mouse.

People use what they are used to, so most people above 30 use Vim or Emacs, and younger people look up to us seniors and emulate what we do, why re-invent the wheel when you see someone using it.

I use Vim for most things, I have tried Emacs but I keep writing :w (save) and just can’t get out of being in Vim. Today I mostly use Visual Studio Code, my fallback is though always Vim. I have years put into the Vim config and I am not going to just forget that.

And last but not least, Vim is fast and easy to use (yes it is) and people like it.

**Comment by Kraaaait** [comment]
♿♿♿♿♿♿♿♿♿♿♿♿♿♿♿♿♿
